#! /bin/sh
hostname linux
mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
telnetd &
#ifconfig lo 127.0.0.1
#ifconfig eth0 hw ether 00:41:00:80:00:00
#ifconfig eth0 192.168.0.102 netmask 255.255.255.0
#ifconfig eth0 192.168.1.3 netmask 255.255.255.0
#ping 192.168.0.105 -c 4

cd /;./start.sh
echo "*********************************************************"
echo " C-SKY CK810 SUPPORT (2009.11)"
echo " For further information check: "
echo " http://www.linux.org/ "
echo "*********************************************************"
