#ifndef __AUDIO_IOCTL_H__
#define __AUDIO_IOCTL_H__

#define AUDIO_IOCTL_MAGIC  'A'

#define AUDIO_IOCTL_GET_IN_START_DMA_ADDR	_IO(AUDIO_IOCTL_MAGIC, 0)
#define AUDIO_IOCTL_GET_IN_DMA_SIZE	        _IO(AUDIO_IOCTL_MAGIC, 1)
#define AUDIO_IOCTL_GET_IN_WR_DMA_ADDR		_IO(AUDIO_IOCTL_MAGIC, 2)

#define AUDIO_IOCTL_GET_OUT_START_DMA_ADDR		_IO(AUDIO_IOCTL_MAGIC, 3)
#define AUDIO_IOCTL_GET_OUT_DMA_SIZE	        _IO(AUDIO_IOCTL_MAGIC, 4)
#define AUDIO_IOCTL_GET_OUT_RD_DMA_ADDR			_IO(AUDIO_IOCTL_MAGIC, 5)

#define AUDIO_IOCTL_IN_TRIGGER		_IO(AUDIO_IOCTL_MAGIC, 6)
#define AUDIO_IOCTL_IN_TRIGGER_OFF		_IO(AUDIO_IOCTL_MAGIC, 7)

#define AUDIO_IOCTL_OUT_TRIGGER		_IO(AUDIO_IOCTL_MAGIC, 8)
#define AUDIO_IOCTL_OUT_TRIGGER_OFF		_IO(AUDIO_IOCTL_MAGIC, 9)

#define AUDIO_IOCTL_SET_IN_CHNS		_IO(AUDIO_IOCTL_MAGIC, 10)
#define AUDIO_IOCTL_SET_IN_BITS		_IO(AUDIO_IOCTL_MAGIC, 11)
#define AUDIO_IOCTL_SET_IN_FS		_IO(AUDIO_IOCTL_MAGIC, 12)

#define AUDIO_IOCTL_SET_OUT_CHNS		_IO(AUDIO_IOCTL_MAGIC, 13)
#define AUDIO_IOCTL_SET_OUT_BITS		_IO(AUDIO_IOCTL_MAGIC, 14)
#define AUDIO_IOCTL_SET_OUT_FS		    _IO(AUDIO_IOCTL_MAGIC, 15)

#endif
