SLLIB_ROOT:=../../..
DEPSRCS := ../../../example/common/sl_file.c
DEPLIBS := slksysctl slmmutil liveMedia  groupsock UsageEnvironment  BasicUsageEnvironment slrtsp slos pthread dl m
include ../../../rule/compile.mk
include ../../../rule/program.mk
